In [1]:
from roboticstoolbox import DHRobot, RevoluteDH
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'roboticstoolbox'

In [1]:
import numpy as np
from math import atan2, sqrt, acos, sin, cos, pi
import matplotlib.pyplot as plt

In [9]:
def load_dh_params(fname='DH_PARAMS.yaml',n=6):
    import yaml
    
    with open(fname, 'r') as f:
        data = yaml.load(f, Loader=yaml.SafeLoader)
    dh_params = []
    links  = list(data.keys())[:n]
    
    for i in links:
        dh_params.append([data[i]['a'],data[i]['alpha'],data[i]['d'],data[i]['theta']])
        
    return dh_params
    
dh_params = load_dh_params()
dh_params = np.round(dh_params,3)
dh_params

array([[-0.   ,  0.   , -0.119,  0.   ],
       [ 0.   ,  0.054, -0.22 ,  0.   ],
       [-0.   ,  0.036, -0.42 ,  0.   ],
       [ 0.   , -0.017, -0.506,  0.   ],
       [ 0.02 , -0.017, -0.563,  0.   ],
       [ 0.   , -0.007, -0.611,  0.   ]])

In [10]:
# Goal Pose
T_06 = np.eye(4)
T_06

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
P_e = T_06[:3,[3]]
Z_6 = T_06[:3,[2]]
x,y,z = P_e.flatten()
x,y,z

(0.0, 0.0, 0.0)

In [21]:
d6 = dh_params[5,2]
W = P_e - d6*Z_6
W

array([[0.   ],
       [0.   ],
       [0.611]])

In [22]:
theta_1 = atan2(y,x)
theta_1 

0.0